{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d8059aa4-8f37-4a4e-b200-2356e7a3845b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/markdown": [
       "The text is a tutorial on fine-tuning language models for specific tasks, such as preference tuning, using tools like LoRA (Low-Rank Adaptation) and DPO (Diversity-Promoting Objective). Here's a summary of the key points:\n",
       "\n",
       "**Introduction**\n",
       "\n",
       "* Fine-tuning allows for persistent changes in model behavior, such as strict output formats, consistent tone, or firm refusal policies.\n",
       "* The goal is to ship models that are safer and more reliable without needing a massive compute cluster.\n",
       "\n",
       "**Choosing Fine-Tuning Methods**\n",
       "\n",
       "* Pick the fine-tuning method based on your compute budget:\n",
       "\t+ LoRA: suitable for small to medium-sized models and GPUs with 24 GB memory.\n",
       "\t+ QLoRA: suitable for larger models and GPUs with 12 GB or more memory.\n",
       "\t+ Full fine-tune: suitable for large models and deep learning frameworks.\n",
       "\n",
       "**Tools and Requirements**\n",
       "\n",
       "* PeFT adapter (tiny): a lightweight, drop-in alternative to DPO.\n",
       "* LoRA merge shocks (sometimes merged weights drift format adherence).\n",
       "* DPO/ORPO (Optimization and Reference Point Optimization): helps with preferences, safety, and consistent tone.\n",
       "* SFT (Self-Tuning Framework) + TDF (Tests-Driven Fine-tuning) harness: for quick fine-tuning iterations.\n",
       "\n",
       "**Experiment Plan**\n",
       "\n",
       "* Curate 300-1,000 SFT exemplars for your task. Template them.\n",
       "* Train SFT for 1-2 epochs. Save adapters every ~200 steps. Run the TDF harness each time.\n",
       "* Create 200-500 preference pairs (prompt + chosen vs rejected). Start with SFT outputs + human edits to bootstrap.\n",
       "* Try different LoRA ranks and max sequence lengths.\n",
       "* Record wall clock and pass rates.\n",
       "\n",
       "**Common Pitfalls**\n",
       "\n",
       "* Wrong chat template: always render data with the exact tokenizer template used at inference.\n",
       "* Data leakage: keep eval prompts disjoint from train; don't mine web Q&A wholesale and report rosy scores.\n",
       "* Over-regularization in DPO: reduce beta or add fresh SFT steps if outputs become terse.\n",
       "\n",
       "**Final Thoughts**\n",
       "\n",
       "* Think of fine-tuning like software engineering: write tests, make small, controlled changes, measure results, and keep good notes.\n",
       "* Know when to not fine-tune. Use RAG (Retrieval-Augmented Generalist) for flexibility, but when you need persistent changes, fine-tune model weights is the better fit.\n",
       "\n",
       "The text concludes by thanking the reader for their attention and inviting them to reach out with questions or suggestions on LinkedIn."
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# A function to display this nicely in the Jupyter output, using markdown\n",
    "import os\n",
    "import requests\n",
    "from dotenv import load_dotenv\n",
    "from bs4 import BeautifulSoup\n",
    "from IPython.display import Markdown, display\n",
    "from openai import OpenAI\n",
    "from openai import OpenAI\n",
    "\n",
    "system_prompt = \"You are an assistant that analyzes the contents of a website \\\n",
    "and provides a short summary, ignoring text that might be navigation-related. \\\n",
    "Respond in markdown.\"\n",
    "\n",
    "# A class to represent a Webpage\n",
    "# If you're not familiar with Classes, check out the \"Intermediate Python\" notebook\n",
    "\n",
    "# Some websites need you to use proper headers when fetching them:\n",
    "headers = {\n",
    " \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36\"\n",
    "}\n",
    "\n",
    "class Website:\n",
    "\n",
    "    def __init__(self, url):\n",
    "        \"\"\"\n",
    "        Create this Website object from the given url using the BeautifulSoup library\n",
    "        \"\"\"\n",
    "        self.url = url\n",
    "        response = requests.get(url, headers=headers)\n",
    "        soup = BeautifulSoup(response.content, 'html.parser')\n",
    "        self.title = soup.title.string if soup.title else \"No title found\"\n",
    "        for irrelevant in soup.body([\"script\", \"style\", \"img\", \"input\"]):\n",
    "            irrelevant.decompose()\n",
    "        self.text = soup.body.get_text(separator=\"\\n\", strip=True)\n",
    "\n",
    "def user_prompt_for(website):\n",
    "    user_prompt = f\"You are looking at a website titled {website.title}\"\n",
    "    user_prompt += \"\\nThe contents of this website is as follows; \\\n",
    "    please provide a short summary of this website in markdown. \\\n",
    "    If it includes news or announcements, then summarize these too.\\n\\n\"\n",
    "    user_prompt += website.text\n",
    "    return user_prompt\n",
    "\n",
    "def messages_for(website):\n",
    "    return [\n",
    "        {\"role\": \"system\", \"content\": system_prompt},\n",
    "        {\"role\": \"user\", \"content\": user_prompt_for(website)}\n",
    "    ]\n",
    "\n",
    "## API from local model running on Ollama \n",
    "ollama_via_openai = OpenAI(base_url='http://localhost:11434/v1', api_key='ollama')\n",
    "\n",
    "# And now: call the local Llama model.\n",
    "MODEL = \"llama3.2\"\n",
    "def summarize(url, MODEL):\n",
    "    website = Website(url)\n",
    "    response = ollama_via_openai.chat.completions.create(\n",
    "        model = MODEL,\n",
    "        messages = messages_for(website)\n",
    "    )\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "# Function to call by providing URL\n",
    "def display_summary(url, Model):\n",
    "    summary = summarize(url)\n",
    "    display(Markdown(summary))\n",
    "\n",
    "### Call function to summarize a webpage\n",
    "display_summary(\"https://medium.com/%40tabers77/llm-fine-tuning-in-2025-a-hands-on-test-driven-blueprint-dd1c7887bb99\", MODEL)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca5a6c79-5859-4962-ad98-ac80fb33b650",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
